# This workflow performs a clean install, caching, building, and testing across Node.js versions

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x] # Include a wider range of supported versions, Using only 20.x now.

    steps:
      - uses: actions/checkout@v4 # Checkout code from the repository
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm" # Cache npm dependencies for faster builds

      - run: npm install # Install project dependencies

      - run: npm run build --prefix client # Build the client-side code (if applicable)

      - name: Check MONGO_URL Secret
        run: echo $MONGO_URL # Print the value for debugging purposes (optional)

      - env: # Define environment variables for tests
          MONGO_URL: ${{ secrets.MONGO_URL }}
        run: npm test # Run tests using the MONGO_URL secret

